# Generated by Django 5.0.6 on 2024-06-15 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptbot',
            name='system_prompt',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='chatgptbot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
